--------------------------------------------------------
--  Fichier créé - mardi-mars-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "AZIZ"."CLIENTS" 
   (	"CIN" NUMBER(20,0), 
	"ID_COMMANDE" NUMBER(20,0), 
	"NOM_CLT" VARCHAR2(20 BYTE), 
	"PRENOM_CLT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "AZIZ"."COMMANDES" 
   (	"ID_COMMANDE" NUMBER(20,0), 
	"PRIX_TOT" NUMBER(20,0), 
	"ID_CLIENT" NUMBER(20,0), 
	"ID_PRODUIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNELS
--------------------------------------------------------

  CREATE TABLE "AZIZ"."PERSONNELS" 
   (	"CIN_PERS" NUMBER, 
	"ID_PRODUIT" NUMBER, 
	"NOM_PERS" VARCHAR2(20 BYTE), 
	"PRENOM_PERS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "AZIZ"."PRODUITS" 
   (	"ID_PRODUIT" NUMBER(20,0), 
	"CIN" NUMBER(20,0), 
	"CIN_PERS" NUMBER(20,0), 
	"ID_COMMANDE" NUMBER(20,0), 
	"CIN_PROMO" NUMBER(20,0), 
	"NOM_PRODUIT" VARCHAR2(20 BYTE), 
	"QUANTITÉ" NUMBER(20,0), 
	"DATE_AJOUT_PRODUIT" DATE, 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTIONS
--------------------------------------------------------

  CREATE TABLE "AZIZ"."PROMOTIONS" 
   (	"CIN_PROMO" NUMBER(20,0), 
	"PROC_PROMO" NUMBER(20,0), 
	"ID_PRODUIT" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REMBOURSEMENT
--------------------------------------------------------

  CREATE TABLE "AZIZ"."REMBOURSEMENT" 
   (	"PRIXT" NUMBER(20,0), 
	"ID_SAV" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SAV
--------------------------------------------------------

  CREATE TABLE "AZIZ"."SAV" 
   (	"ID_SAV" NUMBER(31,0), 
	"NOM" VARCHAR2(200 BYTE), 
	"PRENOM" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"DATE_SAV" VARCHAR2(200 BYTE), 
	"ID_CLIENT" NUMBER(20,0), 
	"REMBOURSEMENT" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AZIZ.CLIENTS
SET DEFINE OFF;
REM INSERTING into AZIZ.COMMANDES
SET DEFINE OFF;
REM INSERTING into AZIZ.PERSONNELS
SET DEFINE OFF;
REM INSERTING into AZIZ.PRODUITS
SET DEFINE OFF;
REM INSERTING into AZIZ.PROMOTIONS
SET DEFINE OFF;
REM INSERTING into AZIZ.REMBOURSEMENT
SET DEFINE OFF;
REM INSERTING into AZIZ.SAV
SET DEFINE OFF;
Insert into AZIZ.SAV (ID_SAV,NOM,PRENOM,DESCRIPTION,DATE_SAV,ID_CLIENT,REMBOURSEMENT) values ('12','aziz','khalsi','uiiuuikkikuuk','02/03/21',null,null);
Insert into AZIZ.SAV (ID_SAV,NOM,PRENOM,DESCRIPTION,DATE_SAV,ID_CLIENT,REMBOURSEMENT) values ('2','aziz','khalsi','is the best','20/02/22',null,null);
Insert into AZIZ.SAV (ID_SAV,NOM,PRENOM,DESCRIPTION,DATE_SAV,ID_CLIENT,REMBOURSEMENT) values ('14','fefed','efzfec','rgvdsdvs','02-jun-0',null,null);
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."CLIENTS_PK" ON "AZIZ"."CLIENTS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."COMMANDES_PK" ON "AZIZ"."COMMANDES" ("ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."PERSONNELS_PK" ON "AZIZ"."PERSONNELS" ("CIN_PERS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."PRODUITS_PK" ON "AZIZ"."PRODUITS" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."PROMOTIONS_PK" ON "AZIZ"."PROMOTIONS" ("CIN_PROMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REMBOURSEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."REMBOURSEMENT_PK" ON "AZIZ"."REMBOURSEMENT" ("PRIXT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."SVA_PK" ON "AZIZ"."SAV" ("ID_SAV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."CLIENTS" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."CLIENTS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "AZIZ"."COMMANDES" ADD CONSTRAINT "COMMANDES_PK" PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."COMMANDES" MODIFY ("PRIX_TOT" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."COMMANDES" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNELS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PERSONNELS" ADD CONSTRAINT "PERSONNELS_PK" PRIMARY KEY ("CIN_PERS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."PERSONNELS" MODIFY ("CIN_PERS" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."PERSONNELS" MODIFY ("PRENOM_PERS" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."PERSONNELS" MODIFY ("NOM_PERS" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."PERSONNELS" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PRODUITS" MODIFY ("CIN_PROMO" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."PRODUITS" ADD CONSTRAINT "PRODUITS_PK" PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."PRODUITS" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."PRODUITS" MODIFY ("CIN_PERS" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."PRODUITS" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."PRODUITS" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTIONS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PROMOTIONS" ADD CONSTRAINT "PROMOTIONS_PK" PRIMARY KEY ("CIN_PROMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."PROMOTIONS" MODIFY ("CIN_PROMO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REMBOURSEMENT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."REMBOURSEMENT" ADD CONSTRAINT "REMBOURSEMENT_PK" PRIMARY KEY ("PRIXT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."REMBOURSEMENT" MODIFY ("PRIXT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SAV
--------------------------------------------------------

  ALTER TABLE "AZIZ"."SAV" ADD CONSTRAINT "SVA_PK" PRIMARY KEY ("ID_SAV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."CLIENTS" ADD CONSTRAINT "CLIENTS_COMMANDE1" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "AZIZ"."COMMANDES" ("ID_COMMANDE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "AZIZ"."COMMANDES" ADD CONSTRAINT "COMMANDES_FK1" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "AZIZ"."CLIENTS" ("CIN") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AZIZ"."COMMANDES" ADD CONSTRAINT "COMMANDES_FK3" FOREIGN KEY ("ID_PRODUIT")
	  REFERENCES "AZIZ"."PRODUITS" ("ID_PRODUIT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONNELS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PERSONNELS" ADD CONSTRAINT "PERSONNELS_FK1" FOREIGN KEY ("ID_PRODUIT")
	  REFERENCES "AZIZ"."PRODUITS" ("ID_PRODUIT") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PRODUITS" ADD CONSTRAINT "PRODUITS_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "AZIZ"."CLIENTS" ("CIN") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AZIZ"."PRODUITS" ADD CONSTRAINT "PRODUITS_FK2" FOREIGN KEY ("CIN_PERS")
	  REFERENCES "AZIZ"."PERSONNELS" ("CIN_PERS") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AZIZ"."PRODUITS" ADD CONSTRAINT "PRODUITS_FK3" FOREIGN KEY ("CIN_PROMO")
	  REFERENCES "AZIZ"."PROMOTIONS" ("CIN_PROMO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AZIZ"."PRODUITS" ADD CONSTRAINT "PRODUITS_FK4" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "AZIZ"."COMMANDES" ("ID_COMMANDE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTIONS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PROMOTIONS" ADD CONSTRAINT "PROMOTIONS_FK1" FOREIGN KEY ("ID_PRODUIT")
	  REFERENCES "AZIZ"."PRODUITS" ("ID_PRODUIT") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REMBOURSEMENT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."REMBOURSEMENT" ADD CONSTRAINT "REMBOURSEMENT_FK1" FOREIGN KEY ("ID_SAV")
	  REFERENCES "AZIZ"."SAV" ("ID_SAV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SAV
--------------------------------------------------------

  ALTER TABLE "AZIZ"."SAV" ADD CONSTRAINT "SAV_FK1" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "AZIZ"."CLIENTS" ("CIN") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AZIZ"."SAV" ADD CONSTRAINT "SAV_FK2" FOREIGN KEY ("REMBOURSEMENT")
	  REFERENCES "AZIZ"."REMBOURSEMENT" ("PRIXT") ENABLE;
